// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgil5--eDlicBCmsGFao64GmUGEFp3w3s',
    appId: '1:7486352821:web:81b8d04bed5144c0fabdfc',
    messagingSenderId: '7486352821',
    projectId: 'cent-8d5ef',
    authDomain: 'cent-8d5ef.firebaseapp.com',
    storageBucket: 'cent-8d5ef.firebasestorage.app',
    measurementId: 'G-Q4MMHQ5N42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3hn4lAPO4ce79kg7LHTAxWZR1aCI8vBU',
    appId: '1:7486352821:android:f5750cc4f3a8a5dbfabdfc',
    messagingSenderId: '7486352821',
    projectId: 'cent-8d5ef',
    storageBucket: 'cent-8d5ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LYR7ZXEORCqL6fNVb4qNU80ssx5EMqc',
    appId: '1:7486352821:ios:a82249efe0cf7845fabdfc',
    messagingSenderId: '7486352821',
    projectId: 'cent-8d5ef',
    storageBucket: 'cent-8d5ef.firebasestorage.app',
    iosBundleId: 'com.example.cent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3LYR7ZXEORCqL6fNVb4qNU80ssx5EMqc',
    appId: '1:7486352821:ios:a82249efe0cf7845fabdfc',
    messagingSenderId: '7486352821',
    projectId: 'cent-8d5ef',
    storageBucket: 'cent-8d5ef.firebasestorage.app',
    iosBundleId: 'com.example.cent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgil5--eDlicBCmsGFao64GmUGEFp3w3s',
    appId: '1:7486352821:web:7087d9ba76c8abdcfabdfc',
    messagingSenderId: '7486352821',
    projectId: 'cent-8d5ef',
    authDomain: 'cent-8d5ef.firebaseapp.com',
    storageBucket: 'cent-8d5ef.firebasestorage.app',
    measurementId: 'G-W93HZWKE4T',
  );
}
